---
# tasks file for ansible-role-nessus


# - ansible.builtin.debug:
#     msg: "{{ (lookup('nessus_download', 'Nessus - 10.4.2', arch='amd64', linux_distro='debian')).url }}"
- name: Install Nessus
  ansible.builtin.apt:
    deb: "{{ (lookup('nessus_download', nessus_version, arch=nessus_arch, linux_distro=nessus_distro)).url }}"
  become: true

- name: Re-provisioning Nessus
  ansible.builtin.file:
    state: absent
    path: "{{ ansible_user_dir }}/.nessus_licensed"
  when:
    - FORCE_NESSUS_PROV is defined
  become: true

- name: Licensing Nessus
  ansible.builtin.command:
    cmd: '{{ nessus_cli }} fetch --register {{ nessus_lic }}'
    creates: '{{ ansible_user_dir }}/.nessus_licensed'
  when: nessus_lic | length > 0
  become: true

- name: Creating file to prevent nessus from configuring again
  ansible.builtin.copy:
    dest: '{{ ansible_user_dir }}/.nessus_licensed'
    content: ""
    mode: "600"
  when: nessus_lic | length > 0
  become: true
